version: '3.9'

services:
#    postgres:
#        image: postgres
#        restart: always
#        # set shared memory limit when using docker-compose
#        shm_size: 128mb
#        environment:
#            POSTGRES_USER: my
#            POSTGRES_PASSWORD: my
#        volumes:
#            - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
#        ports:
#            - "5432:5432"
#        #        network_mode: "host"
#        healthcheck:
#            test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
#            interval: 30s
#            timeout: 60s
#            retries: 5
#            start_period: 80s
#
    listener:
        image: my:mint-event-lister2
        build: /Users/dima/my/solana-event-listener/docker
        environment:
            POSTGRES_PASSWORD: my
            RUST_LOG: info,listener_app=debug,solana_tools=debug
        volumes:
            - ./config.yml:/config.yml
        #        network_mode: "host"
#        depends_on:
#            postgres:
#                condition: service_healthy


